//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_license
    {
        public int id { get; set; }
        public int institute_num { get; set; }
        public Nullable<bool> institute_expired { get; set; }
        public Nullable<System.DateTime> institute_expired_dt { get; set; }
        public int depart_id { get; set; }
        public int depart_num { get; set; }
        public Nullable<bool> depart_expired { get; set; }
        public Nullable<System.DateTime> depart_expired_dt { get; set; }
        public int group_id { get; set; }
        public int group_num { get; set; }
        public Nullable<bool> group_expired { get; set; }
        public Nullable<System.DateTime> group_expired_dt { get; set; }
    
        public virtual department department { get; set; }
        public virtual group group { get; set; }
    }
}
