//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clone_group
    {
        public int id { get; set; }
        public string group_type { get; set; }
        public string name { get; set; }
        public int version { get; set; }
        public int plasmid_id { get; set; }
        public Nullable<int> oligo_id { get; set; }
        public Nullable<int> primer_id { get; set; }
        public Nullable<int> nuclease_id { get; set; }
        public Nullable<int> refgroup { get; set; }
        public string img_fn { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string des { get; set; }
        public Nullable<int> people_id { get; set; }
        public Nullable<bool> submitted_to_group { get; set; }
        public Nullable<bool> shared_with_group { get; set; }
        public string shared_with_people { get; set; }
    
        public virtual oligo oligo { get; set; }
        public virtual person person { get; set; }
        public virtual plasmid plasmid { get; set; }
        public virtual nuclease nuclease { get; set; }
    }
}
