//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_feature
    {
        public int id { get; set; }
        public int feature_id { get; set; }
        public string label { get; set; }
        public string sequence { get; set; }
        public string des { get; set; }
    
        public virtual plasmid_feature plasmid_feature { get; set; }
    }
}
