//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class common_restriction
    {
        public int id { get; set; }
        public int enzyme_id { get; set; }
        public int group_id { get; set; }
    
        public virtual restri_enzyme restri_enzyme { get; set; }
        public virtual group group { get; set; }
    }
}
