//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dcm
    {
        public int id { get; set; }
        public string name { get; set; }
        public bool COverlapping { get; set; }
        public bool CBlocked { get; set; }
        public string prefixing { get; set; }
        public string appending { get; set; }
    }
}
