//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecloningEntities : DbContext
    {
        public ecloningEntities()
            : base("name=ecloningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<clone_group> clone_group { get; set; }
        public virtual DbSet<container> containers { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<dropdownitem> dropdownitems { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<group_people> group_people { get; set; }
        public virtual DbSet<ladder> ladders { get; set; }
        public virtual DbSet<ladder_size> ladder_size { get; set; }
        public virtual DbSet<license> licenses { get; set; }
        public virtual DbSet<main_step> main_step { get; set; }
        public virtual DbSet<minus180_liquid_nitrogen> minus180_liquid_nitrogen { get; set; }
        public virtual DbSet<minus20> minus20 { get; set; }
        public virtual DbSet<minus80> minus80 { get; set; }
        public virtual DbSet<nuclease> nucleases { get; set; }
        public virtual DbSet<oligo> oligoes { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<people_license> people_license { get; set; }
        public virtual DbSet<plasmid> plasmids { get; set; }
        public virtual DbSet<plasmid_feature> plasmid_feature { get; set; }
        public virtual DbSet<plasmid_map> plasmid_map { get; set; }
        public virtual DbSet<primer> primers { get; set; }
        public virtual DbSet<probe> probes { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<protocol> protocols { get; set; }
        public virtual DbSet<restriction> restrictions { get; set; }
        public virtual DbSet<storage> storages { get; set; }
    }
}
