//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_step
    {
        public int id { get; set; }
        public string name { get; set; }
        public int exp_id { get; set; }
        public int type_id { get; set; }
        public int step_id { get; set; }
        public Nullable<int> protocol_id { get; set; }
        public string des { get; set; }
        public int people_id { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    
        public virtual experiment experiment { get; set; }
        public virtual person person { get; set; }
        public virtual protocol protocol { get; set; }
    }
}
