//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fragment_methylation
    {
        public int id { get; set; }
        public int fragment_id { get; set; }
        public int cut { get; set; }
        public int clockwise { get; set; }
        public string name { get; set; }
        public bool dam_complete { get; set; }
        public bool dam_impaired { get; set; }
        public bool dcm_complete { get; set; }
        public bool dcm_impaired { get; set; }
    
        public virtual fragment fragment { get; set; }
    }
}
