//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_people
    {
        public int id { get; set; }
        public int group_id { get; set; }
        public int people_id { get; set; }
    
        public virtual group group { get; set; }
        public virtual person person { get; set; }
    }
}
