//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ladder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ladder()
        {
            this.ladder_size = new HashSet<ladder_size>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> min_bp_kDa { get; set; }
        public Nullable<int> max_bp_kda { get; set; }
        public string company { get; set; }
        public string orderref { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ladder_size> ladder_size { get; set; }
    }
}
