//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ladder_size
    {
        public int id { get; set; }
        public int ladder_id { get; set; }
        public int size { get; set; }
    
        public virtual ladder ladder { get; set; }
    }
}
