//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class minus80
    {
        public int id { get; set; }
        public string name { get; set; }
        public int tower_num { get; set; }
        public int drawer_num { get; set; }
        public int box_num { get; set; }
        public string location { get; set; }
        public string des { get; set; }
    }
}
