//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restriction
    {
        public int id { get; set; }
        public string name { get; set; }
        public string forward_seq { get; set; }
        public int forward_cut { get; set; }
        public string reverse_seq { get; set; }
        public int reverse_cut { get; set; }
        public Nullable<bool> methylation { get; set; }
        public Nullable<bool> common { get; set; }
    }
}
