//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restri_enzyme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restri_enzyme()
        {
            this.activity_restriction = new HashSet<activity_restriction>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string forward_seq { get; set; }
        public int forward_cut { get; set; }
        public int reverse_cut { get; set; }
        public Nullable<bool> staractitivity { get; set; }
        public Nullable<int> inactivation { get; set; }
        public Nullable<bool> dam { get; set; }
        public Nullable<bool> dcm { get; set; }
        public Nullable<bool> cpg { get; set; }
        public Nullable<int> forward_cut2 { get; set; }
        public Nullable<int> reverse_cut2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activity_restriction> activity_restriction { get; set; }
    }
}
