//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecloning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage
    {
        public int id { get; set; }
        public string type { get; set; }
        public string ref_id { get; set; }
        public int container_id { get; set; }
        public Nullable<int> tower_id { get; set; }
        public Nullable<int> drawer_id { get; set; }
        public Nullable<int> box_id { get; set; }
        public string box_label { get; set; }
        public string vial_label { get; set; }
        public Nullable<int> parent_link { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public string des { get; set; }
    }
}
